export const internationalAirports: string[] = [

    // AFRICA
    "Aba Tenna Dejazmach Yilma International Airport (HADR)",
    "Abeid Amani Karume International Airport (HTZA)",
    "Addis Ababa Bole International Airport (HAAB)",
    "Aden Adde International Airport (HCMM)",
    "Ahmed Sékou Touré International Airport (GUCY)",
    "Akanu Ibiam International Airport (DNEN)",
    "Akwa Ibom International Airport (DNAI)",
    "Al Abraq International Airport (HLLQ)",
    "Alexandria International Airport (HEBA)",
    "Amílcar Cabral International Airport (GVAC)",
    "Antonio Agostinho-Neto International Airport (FCPP)",
    "Aristides Pereira International Airport (GVBA)",
    "Asaba International Airport (DNAS)",
    "Asmara International Airport (HHAS)",
    "Assab International Airport (HHSB)",
    "Aswan International Airport (HESN)",
    "Asyut International Airport (HEAT)",
    "Atar International Airport (GQPA)",
    "Bangoka International Airport (FZIC)",
    "Bangui M'Poko International Airport (FEFF)",
    "Banjul International Airport (GBYD)",
    "Bata International Airport (FGBT)",
    "Bayelsa International Airport (DNBY)",
    "Beira International Airport (FQBR)",
    "Bender Qassim International Airport (HCMF)",
    "Benina International Airport (HLLB)",
    "Blaise Diagne International Airport (GOBD)",
    "Bram Fischer International Airport (FABL)",
    "Bujumbura Melchior Ndadaye International Airport (HBBA)",
    "Cairo International Airport (HECA)",
    "Cape Town International Airport (FACT)",
    "Capital International Airport (HECP)",
    "Cesaria Evora International Airport (GVSV)",
    "Chief Dawid Stuurman International Airport (FAPE)",
    "Chileka International Airport (FWCL)",
    "Chinua Achebe International Airport (DNAN)",
    "Chlef Aboubakr Belkaid International Airport (DAOI)",
    "Cotonou Cadjehoun International Airport (DBBB)",
    "Diori Hamani International Airport (DRRN)",
    "Djerba Zarzis International Airport (DTTJ)",
    "Douala International Airport (FKKD)",
    "Dr. Antonio Agostinho Neto International Airport (FNBJ)",
    "Dutse International Airport (DNDS)",
    "Dzaoudzi Pamandzi International Airport (FMCZ)",
    "Egal International Airport (HCMH)",
    "El Alamein International Airport (HEAL)",
    "El Arish International Airport (HEAR)",
    "El Owainat East International Airport (HEOW)",
    "Eldoret International Airport (HKEL)",
    "Enfidha - Hammamet International Airport (DTNH)",
    "Entebbe International Airport (HUEN)",
    "Fes Saïss International Airport (GMFF)",
    "Félix-Houphouët-Boigny International Airport (DIAP)",
    "Gabès Matmata International Airport (DTTG)",
    "Gafsa Ksar International Airport (DTTF)",
    "Gao International Airport (GAGO)",
    "Garoua International Airport (FKKR)",
    "General Tunde Idiagbon International Airport (DNIL)",
    "Gerad Wilwal International Airport (HAJJ)",
    "Goma International Airport (FZNA)",
    "Gombe Lawanti International Airport (DNGO)",
    "Harry Mwanga Nkumbula International Airport (FLLI)",
    "Hawassa International Airport (HALA)",
    "Hosea Kutako International Airport (FYWH)",
    "Hurghada International Airport (HEGN)",
    "Ivato International Airport (FMMI)",
    "Jomo Kenyatta International Airport (HKJK)",
    "Joshua Mqabuko Nkomo International Airport (FVBU)",
    "Juba International Airport (HJJJ)",
    "Julius Nyerere International Airport (HTDA)",
    "Kaduna International Airport (DNKA)",
    "Kamuzu International Airport (FWKI)",
    "Kasane International Airport (FBKE)",
    "Kenneth Kaunda International Airport (FLLS)",
    "Khartoum International Airport (HSSK)",
    "Kigali International Airport (HRYR)",
    "Kilimanjaro International Airport (HTKJ)",
    "King Mswati III International Airport (FDSK)",
    "King Shaka International Airport (FALE)",
    "Kisumu International Airport (HKKI)",
    "Kotoka International Airport (DGAA)",
    "Kruger Mpumalanga International Airport (FAKN)",
    "Laayoune Hassan I International Airport (GMML)",
    "Lanseria International Airport (FALA)",
    "Libreville Leon M'ba International Airport (FOOL)",
    "Lomé–Tokoin International Airport (DXXX)",
    "Lubango Mukanka International Airport (FNUB)",
    "Lubumbashi International Airport (FZQA)",
    "Lungi International Airport (GFLL)",
    "Luxor International Airport (HELX)",
    "Léopold Sédar Senghor International Airport (GOOY)",
    "M'Vengue El Hadj Omar Bongo Ondimba International Airport (FOON)",
    "Maiduguri International Airport (DNMA)",
    "Malabo International Airport (FGSL)",
    "Malakal International Airport (HSSM)",
    "Malindi International Airport (HKML)",
    "Mallam Aminu Kano International Airport (DNKN)",
    "Mano Dayak International Airport (DRZA)",
    "Margaret Ekpo International Airport (DNCA)",
    "Marsa Alam International Airport (HEMA)",
    "Massawa International Airport (HHMS)",
    "Masvingo International Airport (FVMV)",
    "Matsapha International Airport (FDMS)",
    "Maun International Airport (FBMN)",
    "Maya-Maya International Airport (FCBB)",
    "Mersa Matruh International Airport (HEMM)",
    "Mfuwe International Airport (FLMF)",
    "Misrata International Airport (HLMS)",
    "Mitiga International Airport (HLLM)",
    "Mmabatho International Airport (FAMM)",
    "Modibo Keita International Airport (GABS)",
    "Mohamed Boudiaf International Airport (DABC)",
    "Mohammed V International Airport (GMMN)",
    "Moi International Airport (HKMO)",
    "Monastir Habib Bourguiba International Airport (DTMB)",
    "Moshoeshoe I International Airport (FXMM)",
    "Murtala Muhammed International Airport (DNMM)",
    "Mwanza International Airport (HTMW)",
    "N'Djamena International Airport (FTTJ)",
    "Nador Al Aaroui International Airport (GMMW)",
    "Ndjili International Airport (FZAA)",
    "Nelson Mandela International Airport (GVNP)",
    "Niamtougou International Airport (DXNG)",
    "Nnamdi Azikiwe International Airport (DNAA)",
    "Nosy Be-Fascene International Airport (FMNN)",
    "Nouadhibou International Airport (GQPP)",
    "Nouakchott–Oumtounsy International Airport (GQNO)",
    "O.R. Tambo International Airport (FAOR)",
    "Oran Es-Sénia (Ahmed Ben Bella) International Airport (DAOO)",
    "Osvaldo Vieira International Airport (GGOV)",
    "Ouagadougou Thomas Sankara International Airport (DFFD)",
    "Ouarzazate International Airport (GMMZ)",
    "Phillip Gaonwe Matante International Airport (FBFT)",
    "Pilanesberg International Airport (FAPN)",
    "Polokwane International Airport (FAPP)",
    "Port Gentil International Airport (FOOG)",
    "Port Harcourt International Airport (DNPO)",
    "Port Said International Airport (HEPS)",
    "Port Sudan New International Airport (HSPN)",
    "Prempeh I International Airport (DGSI)",
    "President Obiang Nguema International Airport (FGMY)",
    "Prince Said Ibrahim International Airport (FMCH)",
    "Quatro de Fevereiro International Airport (FNLU)",
    "Region of Murcia International Airport (LEMI)",
    "Robert Gabriel Mugabe International Airport (FVHA)",
    "Roberts International Airport (GLRB)",
    "Sadiq Abubakar III International Airport (DNSO)",
    "Saint Catherine International Airport (HESC)",
    "Saint Helena International Airport (FHSH)",
    "Seychelles International Airport (FSIA)",
    "Sfax Thyna International Airport (DTTX)",
    "Simon Mwansa Kapwepwe International Airport (FLSK)",
    "Sir Abubakar Tafawa Balewa Bauchi State International Airport (DNBC)",
    "Sir Seewoosagur Ramgoolam International Airport (FIMP)",
    "Sir Seretse Khama International Airport (FBSK)",
    "Sirt International Airport / Ghardabiya Airbase (HLGD)",
    "Sohag International Airport (HESG)",
    "Sphinx International Airport (HESX)",
    "São Tomé International Airport (FPST)",
    "Taba International Airport (HETB)",
    "Tabarka-Aïn Draham International Airport (DTKA)",
    "Tobruk International Airport (HLTQ)",
    "Tozeur Nefta International Airport (DTTZ)",
    "Tunis Carthage International Airport (DTTA)",
    "Upington International Airport (FAUP)",
    "Victoria Falls International Airport (FVFA)",
    "Walvis Bay International Airport (FYWB)",
    "Welwitschia Mirabilis International Airport (FNMO)",
    "Yakubu Tali International Airport (DGLE)",
    "Yamoussoukro International Airport (DIYO)",
    "Yaoundé Nsimalen International Airport (FKYS)",
    "Zuwarah International Airport (HLZW)",

    // ASIA
    "Abakan International Airport (UNAA)",
    "Adisutjipto International Airport (WARJ)",
    "Adnan Menderes International Airport (LTBJ)",
    "Aji Pangeran Tumenggung Pranoto International Airport (WALS)",
    "Akhmat Kadyrov Grozny International Airport (URMG)",
    "Aktau International Airport (UATE)",
    "Aktobe International Airport (UATT)",
    "Alexander Kartveli Batumi International Airport (UGSB)",
    "Alexei Leonov Kemerovo International Airport (UNEE)",
    "Almaty International Airport (UAAA)",
    "Alykel International Airport (UOOO)",
    "Andijan International Airport (UTKA)",
    "Antalya International Airport (LTAI)",
    "Ashgabat International Airport (UTAA)",
    "Astrakhan Narimanovo Boris M. Kustodiev International Airport (URWA)",
    "Atyrau International Airport (UATG)",
    "Bacolod-Silay International Airport (RPVB)",
    "Baikal International Airport (UIUU)",
    "Baikonur Krayniy International Airport (UAOL)",
    "Baotou Donghe International Airport (ZBOW)",
    "Barnaul Gherman Titov International Airport (UNBB)",
    "Batticaloa International Airport (VCCB)",
    "Beijing Capital International Airport (ZBAA)",
    "Beijing Daxing International Airport (ZBAD)",
    "Ben Gurion International Airport (LLBG)",
    "Bicol International Airport (RPLK)",
    "Biju Patnaik International Airport (VEBS)",
    "Bir Tikendrajit International Airport (VEIM)",
    "Bohol-Panglao International Airport (RPSP)",
    "Brunei International Airport (WBSB)",
    "Bryansk International Airport (UUBP)",
    "Bukhara International Airport (UTSB)",
    "Buyant-Ukhaa International Airport (ZMUB)",
    "Cagayan North International Airport (RPLH)",
    "Calicut International Airport (VOCL)",
    "Cam Ranh International Airport / Cam Ranh Air Base (VVCR)",
    "Can Tho International Airport (VVCT)",
    "Cat Bi International Airport (VVCI)",
    "Changchun Longjia International Airport (ZYCC)",
    "Changsha Huanghua International Airport (ZGHA)",
    "Changzhou Benniu International Airport (ZSCG)",
    "Chania International Airport (LGSA)",
    "Chaudhary Charan Singh International Airport (VILK)",
    "Chengdu Shuangliu International Airport (ZUUU)",
    "Chengdu Tianfu International Airport (ZUTF)",
    "Chennai International Airport (VOMM)",
    "Cheongju International Airport/Cheongju Air Base (K-59/G-513) (RKTU)",
    "Chhatrapati Shivaji Maharaj International Airport (VABB)",
    "Chiang Mai International Airport (VTCC)",
    "Chita-Kadala International Airport (UIAA)",
    "Chongqing Jiangbei International Airport (ZUCK)",
    "Christmas Island International Airport (YPXM)",
    "Chubu Centrair International Airport (RJGG)",
    "Clark International Airport / Clark Air Base (RPLC)",
    "Cochin International Airport (VOCI)",
    "Coimbatore International Airport (VOCB)",
    "Colombo Ratmalana International Airport (VCCC)",
    "Commander in Chief of FALINTIL, Kay Rala Xanana Gusmão, International Airport (WPDB)",
    "Corfu Ioannis Kapodistrias International Airport (LGKR)",
    "Da Nang International Airport (VVDN)",
    "Daegu International Airport (RKTN)",
    "Dalaman International Airport (LTBS)",
    "Dalian Zhoushuizi International Airport (ZYTL)",
    "Dandong Langtou International Airport (ZYDD)",
    "Datong Yungang International Airport (ZBDT)",
    "David the Builder Kutaisi International Airport (UGKO)",
    "Dehong Mangshi International Airport (ZPMS)",
    "Denpasar I Gusti Ngurah Rai International Airport (WADD)",
    "Devi Ahilya Bai Holkar International Airport (VAID)",
    "Don Mueang International Airport (VTBD)",
    "Dortheys Hiyo Eluay International Airport (WAJJ)",
    "Dr. Babasaheb Ambedkar International Airport (VANP)",
    "Dunhuang Mogao International Airport (ZLDH)",
    "Dushanbe International Airport (UTDD)",
    "Ercan International Airport (LCEN)",
    "Erenhot Saiwusu International Airport (ZBER)",
    "Erzurum International Airport (LTCE)",
    "Esenboğa International Airport (LTAC)",
    "Ezhou Huahu International Airport (ZHEC)",
    "Fergana International Airport (UTKF)",
    "Francisco Bangoy International Airport (RPMD)",
    "Fuzhou Changle International Airport (FOC)",
    "Fuzuli International Airport (UBBF)",
    "Gabala International Airport (UBBQ)",
    "Gagarin International Airport (UWSG)",
    "Gan International Airport (VRMG)",
    "Ganja International Airport (UBBG)",
    "Gautam Buddha International Airport (VNBW)",
    "Gaziantep Oğuzeli International Airport (LTAJ)",
    "General Santos International Airport (RPMR)",
    "Gimhae International Airport (RKPK)",
    "Gimpo International Airport (RKSS)",
    "Goa Dabolim International Airport (VOGO)",
    "Golden Ring Yaroslavl International Airport (UUDL)",
    "Guangzhou Baiyun International Airport (ZGGG)",
    "Guilin Liangjiang International Airport (ZGKL)",
    "Guiyang Longdongbao International Airport (ZUGY)",
    "H A S Hanandjoeddin International Airport (WIOD)",
    "Haikou Meilan International Airport (ZJHK)",
    "Halim Perdanakusuma International Airport (WIHH)",
    "Halwara International Airport (VIHX)",
    "Hang Nadim International Airport (WIDD)",
    "Hangzhou Xiaoshan International Airport (ZSHC)",
    "Hanimaadhoo International Airport (VRMH)",
    "Harbin Taiping International Airport (ZYHB)",
    "Hat Yai International Airport (VTSS)",
    "Hazrat Shahjalal International Airport (VGHS)",
    "Hazrat Sultan International Airport (UAIT)",
    "Hefei Xinqiao International Airport (ZSOF)",
    "Heydar Aliyev International Airport (UBBB)",
    "Hohhot Baita International Airport (ZBHH)",
    "Hong Kong International Airport (VHHH)",
    "Huai'an Lianshui International Airport (ZSSH)",
    "Huangshan Tunxi International Airport (ZSTX)",
    "Husein Sastranegara International Airport (WICC)",
    "Ibaraki International Airport (RJAH)",
    "Iloilo International Airport (RPVI)",
    "Incheon International Airport (RKSI)",
    "Indira Gandhi International Airport (VIDP)",
    "Irkutsk International Airport (UIII)",
    "Issyk-Kul International Airport (IKU)",
    "Istanbul Sabiha Gökçen International Airport (LTFJ)",
    "Jaffna International Airport (VCCJ)",
    "Jaipur International Airport (VIJP)",
    "Jeju International Airport (RKPC)",
    "Jiamusi Songjiang International Airport (ZYJM)",
    "Jiayuguan International Airport (ZLJQ)",
    "Jieyang Chaoshan International Airport (ZGOW)",
    "Jinan Yaoqiang International Airport (ZSJN)",
    "Juanda International Airport (WARR)",
    "Juwata International Airport / Suharnoko Harbani AFB (TRK)",
    "Kalibo International Airport (RPVK)",
    "Kannur International Airport (VOKN)",
    "Kansai International Airport (RJBB)",
    "Kaohsiung International Airport (RCKH)",
    "Kashgar Laining International Airport (ZWSH)",
    "Kasteli International Airport(Under Construction) (LGTL)",
    "Kayseri Erkilet International Airport (LTAU)",
    "Kazan International Airport (UWKD)",
    "Kempegowda International Airport Bengaluru (VOBL)",
    "Kertajati International Airport (WICA)",
    "Khujand International Airport (UTDL)",
    "Kogalym International Airport (USRK)",
    "Kokshetau International Airport (UACK)",
    "Korkyt Ata International Airport (UAOO)",
    "Kos International Airport \"Ippokratis\" (LGKO)",
    "Kostanay International Airport (UAUU)",
    "Kota Kinabalu International Airport (WBKK)",
    "Krasnodar Pashkovsky International Airport (URKK)",
    "Krasnoyarsk International Airport (UNKL)",
    "Kuala Lumpur International Airport (WMKK)",
    "Kualanamu International Airport (WIMM)",
    "Kuching International Airport (WBGG)",
    "Kunming Changshui International Airport (ZPPP)",
    "Kurchatov Chelyabinsk International Airport (USCC)",
    "Kushinagar International Airport (VEKI)",
    "Kyushu Saga International Airport (RJFS)",
    "Laguindingan International Airport (RPMY)",
    "Lal Bahadur Shastri International Airport (VEBN)",
    "Langkawi International Airport (WMKL)",
    "Lankaran International Airport (UBBL)",
    "Lanzhou Zhongchuan International Airport (ZLLL)",
    "Laoag International Airport (RPLI)",
    "Larnaca International Airport (LCLK)",
    "Lhasa Gonggar International Airport (ZULS)",
    "Lianyungang Huaguoshan International Airport (ZSLG)",
    "Lijiang Sanyi International Airport (ZPLJ)",
    "Lokpriya Gopinath Bordoloi International Airport (VEGT)",
    "Lombok International Airport (WADL)",
    "Luang Phabang International Airport (VLLB)",
    "Maafaru International Airport (VRDA)",
    "Macau International Airport (VMMC)",
    "Mactan Cebu International Airport (RPVM)",
    "Mae Fah Luang - Chiang Rai International Airport (VTCT)",
    "Magnitogorsk International Airport (USCM)",
    "Maharaja Agrasen International Airport (VIHR)",
    "Makhachkala Uytash International Airport (URML)",
    "Malacca International Airport (WMKM)",
    "Manas International Airport (UAFM)",
    "Mandalay International Airport (VYMD)",
    "Mangaluru International Airport (VOML)",
    "Manohar International Airport (VOGA)",
    "Manshuk Mametova International Airport (UARR)",
    "Mary International Airport (UTAM)",
    "Mattala Rajapaksa International Airport (VCRI)",
    "Meizhou Meixian Changgangji International Airport (ZGMX)",
    "Milas Bodrum International Airport (LTFE)",
    "Minangkabau International Airport (WIPT)",
    "Mopah International Airport (WAKK)",
    "Muan International Airport (RKJB)",
    "Mudanjiang Hailang International Airport (ZYMD)",
    "Naha International Airport (ROAH)",
    "Nakhchivan International Airport (UBBN)",
    "Namangan International Airport (UTFN)",
    "Nanchang Changbei International Airport (ZSCN)",
    "Nanjing Lukou International Airport (ZSNJ)",
    "Nanning Wuxu International Airport (ZGNN)",
    "Nantong Xingdong International Airport (ZSNT)",
    "Narita International Airport (RJAA)",
    "Nashik International Airport (VAOZ)",
    "Navoi International Airport (UTSA)",
    "Nay Pyi Taw International Airport (VYNT)",
    "Netaji Subhash Chandra Bose International Airport (VECC)",
    "Ningbo Lishe International Airport (ZSNB)",
    "Ninoy Aquino International Airport (RPLL)",
    "Nizhneangarsk International Airport (UIUN)",
    "Nizhny Novgorod / Strigino International Airport (UWGG)",
    "Noi Bai International Airport (VVNB)",
    "Nukus International Airport (UTNN)",
    "Nursultan Nazarbayev International Airport (UACC)",
    "Oecusse Route of the Sandalwood International Airport (WPOC)",
    "Ordos Ejin Horo International Airport (ZBDS)",
    "Osaka Itami International Airport (RJOO)",
    "Osh International Airport (UAFO)",
    "Oskemen International Airport (UASK)",
    "Osmany International Airport (VGSY)",
    "Ostafyevo International Airport (UUMO)",
    "Pakse International Airport (VLPS)",
    "Paphos International Airport (LCPH)",
    "Paro International Airport (VQPR)",
    "Pattimura International Airport (WAPP)",
    "Pavlodar International Airport (UASP)",
    "Penang International Airport (WMKP)",
    "Perm International Airport (USPP)",
    "Petropavl International Airport (UACP)",
    "Phnom Penh International Airport (VDPP)",
    "Phu Bai International Airport (VVPB)",
    "Phuket International Airport (VTSP)",
    "Phú Quốc International Airport (VVPQ)",
    "Platon Oyunsky Yakutsk International Airport (UEEE)",
    "Presidente Nicolau Lobato International Airport (WPDL)",
    "Princess Olga Pskov International Airport (ULOO)",
    "Puerto Princesa International Airport / PAF Antonio Bautista Air Base (RPVP)",
    "Pune International Airport (VAPO)",
    "Pyongyang Sunan International Airport (ZKPY)",
    "Qingdao Jiaodong International Airport (ZSQD)",
    "Quanzhou Jinjiang International Airport (ZSQZ)",
    "Qurghonteppa International Airport (UTDT)",
    "Radin Inten II International Airport (WILL)",
    "Raja Bhoj International Airport (VABP)",
    "Raja Haji Fisabilillah International Airport (WIDN)",
    "Rajiv Gandhi International Airport (VOHS)",
    "Rajkot International Airport (VAHS)",
    "Ramon International Airport (LLER)",
    "Rhodes International Airport \"Diagoras\" (LGRP)",
    "Roshchino International Airport (USTR)",
    "Sabetta International Airport (USDA)",
    "Sam Ratulangi International Airport (WAMM)",
    "Samarkand International Airport (UTSS)",
    "Samui International Airport (VTSM)",
    "Sanya Phoenix International Airport (ZJSY)",
    "Sardar Vallabh Patel International Airport (VAAH)",
    "Semei International Airport (UASS)",
    "Senai International Airport (WMKJ)",
    "Shah Amanat International Airport (VGEG)",
    "Shaheed Bhagat Singh International Airport (VICG)",
    "Shanghai Hongqiao International Airport (ZSSS)",
    "Shanghai Pudong International Airport (ZSPD)",
    "Sharm El Sheikh International Airport (HESH)",
    "Sheikh ul Alam International Airport (VISR)",
    "Shenyang Taoxian International Airport (ZYTX)",
    "Shenzhen Bao'an International Airport (ZGSZ)",
    "Shijiazhuang Zhengding International Airport (ZBSJ)",
    "Shirak International Airport (UDSG)",
    "Shirdi International Airport (VASD)",
    "Shymkent International Airport (UAII)",
    "Siem Reap-Angkor International Airport (VDSA)",
    "Sihanouk International Airport (VDSV)",
    "Soekarno-Hatta International Airport (WIII)",
    "Sri Guru Ram Das Ji International Airport (VIAR)",
    "Subic Bay International Airport / Naval Air Station Cubi Point (RPLB)",
    "Sultan Abdul Aziz Shah International Airport (WMSA)",
    "Sultan Aji Muhammad Sulaiman Sepinggan International Airport (WALL)",
    "Sultan Hasanuddin International Airport (WAAA)",
    "Sultan Iskandar Muda International Airport (WITT)",
    "Sultan Syarif Kasim II International Airport / Roesmin Nurjadin AFB (WIBB)",
    "Sunan Shuofang International Airport (ZSWX)",
    "Supadio International Airport (WIOO)",
    "Surat International Airport (VASU)",
    "Surgut International Airport (USRR)",
    "Syamsudin Noor International Airport (WAOO)",
    "Süleyman Demirel International Airport (LTFC)",
    "Taichung International Airport / Ching Chuang Kang Air Base (RCMQ)",
    "Tainan International Airport / Tainan Air Base (RCNN)",
    "Taipei Songshan International Airport (RCSS)",
    "Taiwan Taoyuan International Airport (RCTP)",
    "Taiyuan Wusu International Airport (ZBYN)",
    "Tan Son Nhat International Airport (VVTS)",
    "Taraz International Airport (UADD)",
    "Tashkent International Airport (UTTT)",
    "Tbilisi International Airport (UGTB)",
    "Thiruvananthapuram International Airport (VOTV)",
    "Tianjin Binhai International Airport (ZBTJ)",
    "Tiruchirappalli International Airport (VOTR)",
    "Tirupati International Airport (VOTP)",
    "Tokyo Haneda International Airport (RJTT)",
    "Trabzon International Airport (LTCG)",
    "Tribhuvan International Airport (VNKT)",
    "Turkmenbashi International Airport (UTAK)",
    "Türkmenabat International Airport (UTAV)",
    "U-Tapao–Rayong–Pattaya International Airport (VTBU)",
    "Udon Thani International Airport (VTUD)",
    "Ulaanbaatar Chinggis Khaan International Airport (ZMCK)",
    "Urgench International Airport (UTNU)",
    "Uri Michaeli Haifa International Airport (LLHA)",
    "Vadodara International Airport (VABO)",
    "Van Don International Airport (VVVD)",
    "Veer Savarkar International Airport / INS Utkrosh (VOPB)",
    "Velana International Airport (VRMM)",
    "Vijayawada International Airport (VOBZ)",
    "Villa International Airport Maamigili (VRMV)",
    "Visakhapatnam International Airport (VEVZ)",
    "Vladislav Ardzinba Sukhum International Airport (UGSS)",
    "Vladivostok International Airport (UHWW)",
    "Volgograd International Airport (URWW)",
    "Voronezh International Airport (UUOO)",
    "Wattay International Airport (VLVT)",
    "Wenzhou Longwan International Airport (ZSWZ)",
    "Wonsan Kalma International Airport (ZKWS)",
    "Wuhan Tianhe International Airport (ZHHH)",
    "Xi'an Xianyang International Airport (ZLXY)",
    "Xiamen Gaoqi International Airport (ZSAM)",
    "Xining Caojiabao International Airport (ZLXN)",
    "Xishuangbanna Gasa International Airport (ZPJH)",
    "Xuzhou Guanyin International Airport (ZSXZ)",
    "Yancheng Nanyang International Airport (ZSYN)",
    "Yangon International Airport (VYYY)",
    "Yangyang International Airport (RKNY)",
    "Yantai Penglai International Airport (ZSYT)",
    "Yinchuan Hedong International Airport (ZLIC)",
    "Yogyakarta International Airport (WAHI)",
    "Yuncheng Yanhu International Airport (ZBYC)",
    "Zamboanga International Airport (RPMZ)",
    "Zangilan International Airport (UBBZ)",
    "Zaqatala International Airport (UBBY)",
    "Zhangjiajie Hehua International Airport (ZGDY)",
    "Zhanjiang Wuchuan International Airport (ZGZJ)",
    "Zhengzhou Xinzheng International Airport (ZHCC)",
    "Zhukovsky International Airport (UUBW)",
    "Zvartnots International Airport (UDYZ)",
    "Çukurova International Airport (LTDB)",
    "Ölgii Mongolei International Airport (ZMUL)",
    "Ürümqi Tianshan International Airport (ZWWW)",

    // AUSTRALIA & OCEANIA
    "Adelaide International Airport (YPAD)",
    "Antonio B. Won Pat International Airport (GUM)",
    "Auckland International Airport (NZAA)",
    "Bauerfield International Airport (NVVV)",
    "Bonriki International Airport (NGTA)",
    "Brisbane International Airport (YBBN)",
    "Broome International Airport (YBRM)",
    "Cairns International Airport (YBCS)",
    "Cassidy International Airport (PLCH)",
    "Christchurch International Airport (NZCH)",
    "Chuuk International Airport (TKK)",
    "Darwin International Airport / RAAF Darwin (YPDN)",
    "Dunedin International Airport (NZDN)",
    "Ellison Onizuka Kona International Airport at Keāhole (KOA)",
    "Fa'a'ā International Airport (NTAA)",
    "Faleolo International Airport (NSFA)",
    "Fua'amotu International Airport (NFTF)",
    "Funafuti International Airport (NGFU)",
    "Hamilton International Airport (NZHN)",
    "Hilo International Airport (ITO)",
    "Hobart International Airport (YMHB)",
    "Honiara International Airport (AGGH)",
    "Kahului International Airport (OGG)",
    "Kosrae International Airport (TTK)",
    "La Tontouta International Airport (NWWW)",
    "Marshall Islands International Airport (MAJ)",
    "Melbourne Avalon International Airport (YMAV)",
    "Nadi International Airport (NFFN)",
    "Nadzab Tomodachi International Airport (AYNZ)",
    "Nauru International Airport (ANYN)",
    "Nausori International Airport (NFNA)",
    "Niue International Airport (NIUE)",
    "Norfolk Island International Airport (YSNF)",
    "Pago Pago International Airport (PPG)",
    "Perth International Airport (YPPH)",
    "Pohnpei International Airport (PNI)",
    "Port Hedland International Airport (YPPD)",
    "Port Moresby Jacksons International Airport (AYPY)",
    "Rarotonga International Airport (NCRG)",
    "Roman Tmetuchl International Airport (ROR)",
    "Rota International Airport (GRO)",
    "Saipan International Airport (GSN)",
    "Santo Pekoa International Airport (NVSS)",
    "Sydney Kingsford Smith International Airport (YSSY)",
    "Tinian International Airport (TNI)",
    "Vava'u International Airport (NFTV)",
    "Wellington International Airport (NZWN)",
    "Wewak International Airport (AYWK)",
    "Yap International Airport (T11)",

    // EUROPE
    "Aberdeen International Airport (EGPD)",
    "Akureyri International Airport (BIAR)",
    "Antwerp International Airport (Deurne) (EBAW)",
    "Arad International Airport (LRAR)",
    "Athens Eleftherios Venizelos International Airport (LGAV)",
    "Avram Iancu Cluj International Airport (LRCL)",
    "Banja Luka International Airport (LQBK)",
    "Bari Karol Wojtyła International Airport (LIBD)",
    "Bastia-Poretta International airport (LFKB)",
    "Belfast International Airport (EGAA)",
    "Belgorod International Airport (UUOB)",
    "Boryspil International Airport (UKBB)",
    "Brașov-Ghimbav International Airport (LRBV)",
    "Breda International Airport (EHSE)",
    "Brest International Airport (UMBB)",
    "Bucharest Băneasa Aurel Vlaicu International Airport (LRBS)",
    "Bucharest Henri Coandă International Airport (LROP)",
    "Budapest Liszt Ferenc International Airport (LHBP)",
    "Bălți International Airport (LUBL)",
    "Cahul International Airport (LUCH)",
    "Cardiff International Airport (EGFF)",
    "Charles de Gaulle International Airport (LFPG)",
    "Cherkasy International Airport (UKKE)",
    "Chernivtsi International Airport (UKLN)",
    "Chişinău International Airport (LUKK)",
    "Ciampino–G. B. Pastine International Airport (LIRA)",
    "Ciudad Real International Airport (LERL)",
    "Cork International Airport (EICK)",
    "Craiova International Airport (LRCV)",
    "Cristiano Ronaldo International Airport (LPMA)",
    "Cuneo International Airport (LIMZ)",
    "Debrecen International Airport (LHDC)",
    "Dnipro International Airport (UKDD)",
    "Domodedovo International Airport (UUDD)",
    "Exeter International Airport (EGTE)",
    "Faro - Gago Coutinho International Airport (LPFR)",
    "Federico Fellini International Airport (LIPR)",
    "Flanders International Airport Kortrijk-Wevelgem (EBKT)",
    "Forlì-Luigi Ridolfi International Airport (LIPK)",
    "Geneva Cointrin International Airport (LSGG)",
    "Iaşi International Airport (LRIA)",
    "Ihor Sikorsky Kyiv International Airport (Zhuliany) (UKKK)",
    "Il Caravaggio International Airport (LIME)",
    "Ivano-Frankivsk International Airport (UKLI)",
    "Katowice Wojciech Korfanty International Airport (EPKT)",
    "Kaunas International Airport (EYKA)",
    "Kavala Alexander the Great International Airport (LGKV)",
    "Keflavik International Airport (BIKF)",
    "Kharkiv International Airport (UKHH)",
    "Kherson International Airport (UKOH)",
    "Kittilä International Airport (EFKT)",
    "Košice International Airport (LZKZ)",
    "Kraków John Paul II International Airport (EPKK)",
    "Kryvyi Rih International Airport (UKDR)",
    "Kukës International Airport (LAKU)",
    "Kurumoch International Airport (UWWW)",
    "Lamezia Terme Sant'Eufemia International Airport (LICA)",
    "Liepāja International Airport (EVLA)",
    "Luxembourg-Findel International Airport (ELLX)",
    "Lviv International Airport (UKLL)",
    "Malta International Airport (LMML)",
    "Maramureș International Airport (LRBM)",
    "Mariupol International Airport (UKCM)",
    "Mihail Kogălniceanu International Airport (LRCK)",
    "Milan Malpensa International Airport (LIMC)",
    "Mostar International Airport (LQMO)",
    "Mykolaiv International Airport (UKON)",
    "Mytilene International Airport (LGMT)",
    "Naples International Airport (LIRN)",
    "Newcastle International Airport (EGNT)",
    "Odesa International Airport (UKOO)",
    "Oradea International Airport (LROD)",
    "Oslo-Gardermoen International Airport (ENGM)",
    "Ostend-Bruges International Airport (EBOS)",
    "Palanga International Airport (EYPA)",
    "Paris-Le Bourget International Airport (LFPB)",
    "Perugia San Francesco d'Assisi – Umbria International Airport (LIRZ)",
    "Pisa International Airport (LIRP)",
    "Platov International Airport (URRP)",
    "Plovdiv International Airport (LBPD)",
    "Priština Adem Jashari International Airport (BKPR)",
    "Pécs-Pogány International Airport (LHPP)",
    "Riga International Airport (EVRA)",
    "Riviera Villanova d'Albenga International Airport (LIMG)",
    "Rivne International Airport (UKLR)",
    "Rome–Fiumicino Leonardo da Vinci International Airport (LIRF)",
    "Santorini International Airport (LGSR)",
    "Sarajevo International Airport (LQSA)",
    "Saransk International Airport (UWPS)",
    "Satu Mare International Airport (LRSM)",
    "Sevastopol International Airport / Belbek Air Base (UKFB)",
    "Sheremetyevo International Airport (UUEE)",
    "Sibiu International Airport (LRSB)",
    "Simferopol International Airport (UKFF)",
    "Skopje International Airport (LWSK)",
    "Sochi International Airport (URSS)",
    "Suceava Ștefan cel Mare International Airport (LRSV)",
    "Teesside International Airport (EGNV)",
    "Ternopil International Airport (UKLT)",
    "Texel International Airport (EHTX)",
    "Thessaloniki Macedonia International Airport (LGTS)",
    "Timișoara Traian Vuia International Airport (LRTR)",
    "Tirana International Airport Mother Teresa (LATI)",
    "Tuzla International Airport (LQTZ)",
    "Târgu Mureş Transilvania International Airport (LRTM)",
    "Ufa International Airport (UWUU)",
    "Uzhhorod International Airport (UKLU)",
    "Ventspils International Airport (EVVA)",
    "Vienna International Airport (LOWW)",
    "Vilnius International Airport (EYVI)",
    "Vinnytsia/Gavyryshivka International Airport (UKWW)",
    "Vladikavkaz Beslan International Airport (URMO)",
    "Vnukovo International Airport (UUWW)",
    "Zagreb Franjo Tuđman International Airport (LDZA)",
    "Zakynthos International Airport Dionysios Solomos (LGZA)",
    "Zaporizhzhia International Airport (UKDE)",
    "Šiauliai International Airport (EYSA)",

    // MIDDLE EAST
    "Abadan Ayatollah Jami International Airport (OIAA)",
    "Abha International Airport (OEAB)",
    "Aden International Airport (OYAA)",
    "Ahmad Shah Baba International Airport / Kandahar Airfield (OAKN)",
    "Al Ain International Airport (OMAL)",
    "Al Ghaydah International Airport (OYGD)",
    "Al Maktoum International Airport (OMDW)",
    "Al Najaf International Airport (ORNI)",
    "Al-Ahsa International Airport (OEAH)",
    "Al-Jawf International Airport (OESK)",
    "Al-Ula International Airport (OEAO)",
    "Aleppo International Airport (OSAP)",
    "Ayatollah Hashemi Rafsanjani International Airport (OIKK)",
    "Baghdad International Airport / New Al Muthana Air Base (ORBI)",
    "Bahrain International Airport (OBBI)",
    "Bandar Abbas International Airport (OIKB)",
    "Bandar Lengeh International Airport (OIBL)",
    "Basra International Airport (ORMM)",
    "Beirut Rafic Hariri International Airport (OLBA)",
    "Birjand International Airport (OIMB)",
    "Chabahar Konarak International Airport (ZBR)",
    "Damascus International Airport (OSDI)",
    "Doha International Airport (OTBD)",
    "Dubai International Airport (OMDB)",
    "Erbil International Airport (ORER)",
    "Fujairah International Airport (OMFJ)",
    "Hamad International Airport (OTHH)",
    "Herat - Khwaja Abdullah Ansari International Airport (OAHR)",
    "Hodeida International Airport (OYHD)",
    "Imam Khomeini International Airport (OIIE)",
    "Isfahan Shahid Beheshti International Airport (OIFM)",
    "Kabul International Airport (OAKB)",
    "Khost International Airport (OAKS)",
    "King Abdulaziz International Airport (OEJN)",
    "King Fahd International Airport (OEDF)",
    "King Hussein International Airport (OJAQ)",
    "King Khalid International Airport (OERK)",
    "Kirkuk International Airport (ORKK)",
    "Kish International Airport (OIBK)",
    "Kuwait International Airport (OKKK)",
    "Latakia International Airport (OSLK)",
    "Mashhad International Airport (OIMM)",
    "Mazar-i-Sharif International Airport (OAMS)",
    "Mehrabad International Airport (OIII)",
    "Mosul International Airport (ORBM)",
    "Muscat International Airport (OOMS)",
    "Payam Karaj International Airport (OIIP)",
    "Persian Gulf International Airport (OIBP)",
    "Prince Abdulmohsen Bin Abdulaziz International Airport (OEYN)",
    "Prince Naif bin Abdulaziz International Airport (OEGS)",
    "Prince Sultan bin Abdulaziz International Airport (OETB)",
    "Qamishli International Airport (OSKL)",
    "Qasem Soleimani International Airport (OIAW)",
    "Qeshm International Airport (OIKQ)",
    "Queen Alia International Airport (OJAI)",
    "Ras Al Khaimah International Airport (OMRK)",
    "Riyan International Airport (OYRN)",
    "Salalah International Airport (OOSA)",
    "Sanaa International Airport (OYSN)",
    "Sari Dasht-e Naz International Airport (OINZ)",
    "Seiyun Hadhramaut International Airport (OYSY)",
    "Shahrud International Airport (OIMJ)",
    "Sharjah International Airport (OMSJ)",
    "Shiraz Shahid Dastghaib International Airport (OISS)",
    "Suhar International Airport (OOSH)",
    "Sulaymaniyah International Airport (OSO)",
    "Tabriz International Airport (OITT)",
    "Taif International Airport (OETF)",
    "Taiz International Airport (OYTZ)",
    "Zahedan International Airport (OIZH)",
    "Zayed International Airport (OMAA)",

    // OTHERS
    "A.N.R. Robinson International Airport (TTCP)",
    "Abbotsford International Airport (CYXX)",
    "Abel Santamaria International Airport (MUSC)",
    "Abraham González International Airport (MMCS)",
    "Adolfo López Mateos International Airport (MMTO)",
    "Akron Fulton International Airport (AKR)",
    "Albany International Airport (ALB)",
    "Alexandria International Airport (AEX)",
    "Alice International Airport (ALI)",
    "Angel Albino Corzo International Airport (TGZ)",
    "Antoine-Simon International Airport (MTCA)",
    "Antonio Maceo International Airport (MUCU)",
    "Appleton International Airport (ATW)",
    "Argyle International Airport (TVSA)",
    "Arkansas International Airport (BYH)",
    "Arturo Michelena International Airport (SVVA)",
    "Atlantic City International Airport (ACY)",
    "Augusto C. Sandino (Managua) International Airport (MNMG)",
    "Austin Bergstrom International Airport (AUS)",
    "Austin Straubel International Airport (GRB)",
    "Bachigualato Federal International Airport (MMCL)",
    "Bahías de Huatulco International Airport (HU1)",
    "Bangor International Airport (BGR)",
    "Baudette International Airport (BDE)",
    "Bellingham International Airport (BLI)",
    "Benito Juárez International Airport (ME1)",
    "Billings Logan International Airport (BIL)",
    "Birmingham-Shuttlesworth International Airport (BHM)",
    "Bisbee Douglas International Airport (DUG)",
    "Bishop International Airport (FNT)",
    "Bocas del Toro \"Isla Colón\" International Airport (MPBO)",
    "Bozeman Yellowstone International Airport (BZN)",
    "Bradley International Airport (BDL)",
    "Brownsville South Padre Island International Airport (BRO)",
    "Buffalo Niagara International Airport (BUF)",
    "Cabo San Lucas International Airport (CSL)",
    "Calexico International Airport (CXL)",
    "Calgary International Airport (CYYC)",
    "Camarillo International Airport (CMA)",
    "Cancún International Airport (MMUN)",
    "Cap Haitien International Airport (MTCH)",
    "Capital Region International Airport (LAN)",
    "Carlos Rovirosa Pérez International Airport (MMVA)",
    "Casa De Campo International Airport (MDLR)",
    "Casper-Natrona County International Airport (CPR)",
    "Changuinola Captain Manuel Niño International Airport (MPCH)",
    "Charles Kirkconnell International Airport (MWCB)",
    "Charleston International Airport (CHS)",
    "Charlotte Douglas International Airport (CLT)",
    "Chennault International Airport (CWF)",
    "Chetumal International Airport (MMCM)",
    "Chicago Midway International Airport (MDW)",
    "Chicago O'Hare International Airport (ORD)",
    "Chicago Rockford International Airport (RFD)",
    "Chichén Itzá International Airport (MMCT)",
    "Chippewa County International Airport (CIU)",
    "Cibao International Airport (MDST)",
    "Cincinnati Northern Kentucky International Airport (CVG)",
    "Ciudad Acuña New International Airport (EFN)",
    "Ciudad Obregón International Airport (MMCN)",
    "Ciudad del Carmen International Airport (MMCE)",
    "Clayton J. Lloyd International Airport (TQPF)",
    "Cleveland Hopkins International Airport (CLE)",
    "Cobb County International Airport-McCollum Field (RYY)",
    "Comox Valley International Airport / CFB Comox (CYQQ)",
    "Corpus Christi International Airport (CRP)",
    "Cozumel International Airport (MMCZ)",
    "Cranbrook/Canadian Rockies International Airport (CYXC)",
    "Cut Bank International Airport (CTB)",
    "Dallas Fort Worth International Airport (DFW)",
    "Daniel K. Inouye International Airport (HNL)",
    "Daniel Oduber Quirós International Airport (MRLB)",
    "Daytona Beach International Airport (DAB)",
    "Del Caribe Santiago Mariño International Airport (SVMG)",
    "Del Norte International Airport (ADN)",
    "Del Rio International Airport (DRT)",
    "Denver International Airport (DEN)",
    "Des Moines International Airport (DSM)",
    "Duluth International Airport (DLH)",
    "Edmonton International Airport (CYEG)",
    "El Paso International Airport (ELP)",
    "El Salvador International Airport Saint Óscar Arnulfo Romero y Galdámez (MSLP)",
    "Enrique Malek International Airport (MPDA)",
    "Ensenada International Airport / El Ciprés Air Base (ENS)",
    "Exuma International Airport (MYEF)",
    "Fairbanks International Airport (FAI)",
    "Falls International Airport (INL)",
    "Felipe Carrillo Puerto International Airport Tulum (MMTL)",
    "Flamingo International Airport (TNCB)",
    "Florida Keys Marathon International Airport (MTH)",
    "Fort Lauderdale Hollywood International Airport (FLL)",
    "Fort McMurray International Airport (CYMM)",
    "Fort Wayne International Airport (FWA)",
    "Fort Worth Meacham International Airport (FTW)",
    "Francisco Sarabia Tinoco International Airport (MMTC)",
    "Frank Pais International Airport (MUHG)",
    "Frederick Douglass Greater Rochester International Airport (ROC)",
    "Fredericton International Airport (CYFC)",
    "Fresno Yosemite International Airport (FAT)",
    "Gander International Airport (CYQX)",
    "Gary Chicago International Airport (GYY)",
    "General Abelardo L. Rodriguez International Airport (MMTJ)",
    "General Edward Lawrence Logan International Airport (BOS)",
    "General Felipe Ángeles International Airport (SLM)",
    "General Francisco J. Mujica International Airport (MMMM)",
    "General Francisco Javier Mina International Airport (MMTM)",
    "General Guadalupe Victoria International Airport (MMDO)",
    "General Heriberto Jara International Airport (MMVR)",
    "General Ignacio L. Pesqueira International Airport (MMHO)",
    "General José María Yáñez International Airport (MMGM)",
    "General Juan N. Álvarez International Airport (MMAA)",
    "General Leobardo C. Ruiz International Airport (MMZC)",
    "General Lucio Blanco International Airport (REI)",
    "General Manuel Carlos Piar International Airport (SVPR)",
    "General Mariano Matamoros International Airport (MMCB)",
    "General Mitchell International Airport (MKE)",
    "General Pedro Jose Mendez International Airport (MMCV)",
    "General Rafael Buelna International Airport (MMMZ)",
    "General Roberto Fierro Villalobos International Airport (MMCU)",
    "General Rodolfo Sánchez Taboada International Airport (M1L)",
    "General Servando Canales International Airport (MMMA)",
    "General Wayne A. Downing Peoria International Airport (PIA)",
    "Gerald R. Ford International Airport (GRR)",
    "Glacier Park International Airport (GPI)",
    "Golosón International Airport (MHLC)",
    "Grand Bahama International Airport (MYGF)",
    "Grand Forks International Airport (GFK)",
    "Grant County International Airport (MWH)",
    "Grantley Adams International Airport (TBPB)",
    "Great Falls International Airport (GTF)",
    "Greater Moncton Roméo LeBlanc International Airport (CYQM)",
    "Greenville-Spartanburg International Airport (GSP)",
    "Gregorio Luperon International Airport (MDPP)",
    "Griffiss International Airport (RME)",
    "Guadalajara International Airport (GDL)",
    "Guanajuato International Airport (BJ1)",
    "Gulfport Biloxi International Airport (GPT)",
    "Gustavo Rojas Pinilla International Airport (ADZ)",
    "Halifax / Stanfield International Airport (CYHZ)",
    "Harold Charles International Airport (MBAC)",
    "Harrisburg International Airport (MDT)",
    "Harry Reid International Airport (LAS)",
    "Hartsfield Jackson Atlanta International Airport (ATL)",
    "Hato International Airport (TNCC)",
    "Hector International Airport (FAR)",
    "Hermanos Serdán International Airport (MMPB)",
    "Hewanorra International Airport (TLPL)",
    "Houlton International Airport (HUL)",
    "Huntsville International Airport (HSV)",
    "Ian Fleming International Airport (MKBS)",
    "Ignacio Agramonte International Airport (MUCM)",
    "Ilopango International Airport (MSSS)",
    "Indianapolis International Airport (IND)",
    "Ingeniero Alberto Acuña Ongay International Airport (MMCP)",
    "Ixtapa-Zihuatanejo International Airport (MMZH)",
    "JAGS McCartney International Airport (MBGT)",
    "Jacinto Lara International Airport (SVBM)",
    "Jackson-Medgar Wiley Evers International Airport (JAN)",
    "Jacksonville International Airport (JAX)",
    "James M. Cox Dayton International Airport (DAY)",
    "Jesús Terán Peredo International Airport (MMAS)",
    "John C. Munro Hamilton International Airport (CYHM)",
    "John F. Kennedy International Airport (JFK)",
    "John Glenn Columbus International Airport (CMH)",
    "John Wayne Orange County International Airport (SNA)",
    "José Martí International Airport (MUHA)",
    "Juan Gualberto Gomez International Airport (MUVR)",
    "Juan Manuel Gálvez International Airport (MHRO)",
    "Juan Santamaría International Airport (MROC)",
    "Juneau International Airport (JNU)",
    "Kalamazoo/Battle Creek International Airport (AZO)",
    "Kangerlussuaq International Airport (BGSF)",
    "Kansas City International Airport (MCI)",
    "Kelowna International Airport (CYLW)",
    "Ketchikan International Airport (KTN)",
    "Key West International Airport (EYW)",
    "King County International Airport - Boeing Field (BFI)",
    "L.F. Wade International Airport (TXKF)",
    "La Aurora International Airport (MGGT)",
    "La Isabela International Airport (MDJB)",
    "Lakeland Linder International Airport (LAL)",
    "Laredo International Airport (LRD)",
    "Las Américas International Airport (MDSD)",
    "Las Cruces International Airport (LRU)",
    "Laughlin Bullhead International Airport (IFP)",
    "Lawrenceville Vincennes International Airport (LWV)",
    "Leesburg International Airport (LEE)",
    "Lehigh Valley International Airport (ABE)",
    "Leonard M. Thompson International Airport (MYAM)",
    "Licenciado Miguel de la Madrid International Airport (COL)",
    "Limón International Airport (MRLM)",
    "London International Airport (CYXU)",
    "Long Beach International Airport (LGB)",
    "Loreto International Airport (MMLT)",
    "Los Angeles International Airport (LAX)",
    "Los Cabos International Airport (MMSD)",
    "Louis Armstrong New Orleans International Airport (MSY)",
    "Louisville Muhammad Ali International Airport (SDF)",
    "Lubbock Preston Smith International Airport (LBB)",
    "Luis Munoz Marin International Airport (SJU)",
    "Lynden Pindling International Airport (MYNN)",
    "MBS International Airport (MBS)",
    "Manuel Crescencio Rejón International Airport (MMMD)",
    "Manuel Márquez de León International Airport (MMLP)",
    "Mar de Cortés International Airport (AMC)",
    "Marcos A. Gelabert International Airport (MPMG)",
    "Maria Montez International Airport (MDBH)",
    "Marquette/Sawyer International Airport (SAW)",
    "Martinique Aimé Césaire International Airport (TFFF)",
    "Maryse Condé International Airport (TFFR)",
    "Massena International Airport Richards Field (MSS)",
    "Maurice Bishop International Airport (TGPY)",
    "McAllen Miller International Airport (MFE)",
    "Melbourne Orlando International Airport (MLB)",
    "Memphis International Airport (MEM)",
    "Mercedita International Airport (PSE)",
    "Miami International Airport (MIA)",
    "Minatitlán/Coatzacoalcos International Airport (MMMT)",
    "Minneapolis–Saint Paul International Airport / Wold–Chamberlain Field (MSP)",
    "Minot International Airport (MOT)",
    "Monclova International Airport (MOV)",
    "Mont-Tremblant International Airport (CYFJ)",
    "Monterrey International Airport (MMMY)",
    "Montreal / Pierre Elliott Trudeau International Airport (YUL)",
    "Montreal Mirabel International Airport (CYMX)",
    "Mundo Maya International Airport (MGTK)",
    "Myrtle Beach International Airport (MYR)",
    "Narsarsuaq International Airport (BGBW)",
    "Nashville International Airport (BNA)",
    "New York Stewart International Airport (SWF)",
    "Newark Liberty International Airport (EWR)",
    "Newport News Williamsburg International Airport (PHF)",
    "Niagara Falls International Airport (IAG)",
    "Nogales International Airport (OLS)",
    "Nogales International Airport (MMNG)",
    "Norfolk International Airport (ORF)",
    "Norman Manley International Airport (MKJP)",
    "Norman Y. Mineta San Jose International Airport (SJC)",
    "Northeast Kingdom International Airport (EFK)",
    "Northwest Florida Beaches International Airport (ECP)",
    "Nuuk International Airport (BGGH)",
    "Oakland County International Airport (PTK)",
    "Ocala International Airport - Jim Taylor Field (OCF)",
    "Ogdensburg International Airport (OGS)",
    "Ontario International Airport (ONT)",
    "Orlando International Airport (MCO)",
    "Orlando Sanford International Airport (SFB)",
    "Ottawa Macdonald-Cartier International Airport (YOW)",
    "Owen Roberts International Airport (MWCR)",
    "Palenque International Airport (MMPQ)",
    "Palm Beach International Airport (PBI)",
    "Palm Springs International Airport (PSP)",
    "Palmerola International Airport (MHSC)",
    "Panamá Pacífico International Airport (MPHO)",
    "Patrick Leahy Burlington International Airport (BTV)",
    "Pensacola International Airport (PNS)",
    "Philadelphia International Airport (PHL)",
    "Philip S. W. Goldson International Airport (MZBZ)",
    "Phoenix Sky Harbor International Airport (PHX)",
    "Piarco International Airport (TTPP)",
    "Piedmont Triad International Airport (GSO)",
    "Piedras Negras International Airport (PNG)",
    "Pittsburgh International Airport (PIT)",
    "Plan De Guadalupe International Airport (MMIO)",
    "Plattsburgh International Airport (PBG)",
    "Playa de Oro International Airport (MMZO)",
    "Ponciano Arriaga International Airport (MMSP)",
    "Portland International Airport (PDX)",
    "Portsmouth International Airport at Pease (PSM)",
    "Presidio Lely International Airport (PRS)",
    "Presque Isle International Airport (PQI)",
    "Princess Juliana International Airport (TNCM)",
    "Providenciales International Airport (MBPV)",
    "Puerto Escondido International Airport (P1M)",
    "Puerto Vallarta International Airport (MMPR)",
    "Punta Cana International Airport (MDPC)",
    "Quad City International Airport (MLI)",
    "Quebec Jean Lesage International Airport (YQB)",
    "Queen Beatrix International Airport (TNCA)",
    "Quetzalcóatl International Airport (MMNL)",
    "Rafael Hernández International Airport (BQN)",
    "Raleigh-Durham International Airport (RDU)",
    "Ramón Villeda Morales International Airport (MHLM)",
    "Regina International Airport (CYQR)",
    "Region of Waterloo International Airport (CYKF)",
    "Reno Tahoe International Airport (RNO)",
    "Rhode Island T. F. Green International Airport (PVD)",
    "Richmond International Airport (RIC)",
    "Rick Husband Amarillo International Airport (AMA)",
    "Rickenbacker International Airport (LCK)",
    "Robert L. Bradshaw International Airport (TKPK)",
    "Rochester International Airport (RST)",
    "Rock Sound International Airport (MYER)",
    "Rum Cay International Airport (MYRP)",
    "Sacramento International Airport (SMF)",
    "Salt Lake City International Airport (SLC)",
    "Samaná El Catey International Airport (MDCY)",
    "San Antonio International Airport (SAT)",
    "San Bernardino International Airport (SBD)",
    "San Diego International Airport (SAN)",
    "San Felipe International Airport (SFE)",
    "San Francisco Bay Oakland International Airport (OAK)",
    "San Francisco International Airport (SFO)",
    "San Salvador International Airport (MYSM)",
    "Sangster International Airport (MKJS)",
    "Sarasota Bradenton International Airport (SRQ)",
    "Saskatoon John G. Diefenbaker International Airport (CYXE)",
    "Savannah Hilton Head International Airport (SAV)",
    "Scarlett Martinez International Airport (MPSM)",
    "Seattle Paine Field International Airport (PAE)",
    "Seattle–Tacoma International Airport (SEA)",
    "Sierra Maestra International Airport (MUMZ)",
    "South Bend International Airport (SBN)",
    "Southwest Florida International Airport (RSW)",
    "Spokane International Airport (GEG)",
    "St Clair County International Airport (PHN)",
    "St. John's International Airport (CYYT)",
    "St. Louis Lambert International Airport (STL)",
    "St. Petersburg Clearwater International Airport (PIE)",
    "Stennis International Airport (HSA)",
    "Stephenville Dymond International Airport (CYJT)",
    "Sullivan County International Airport (MSV)",
    "Syracuse Hancock International Airport (SYR)",
    "Tallahassee International Airport (TLH)",
    "Tampa International Airport (TPA)",
    "Tapachula International Airport (MMTP)",
    "Ted Stevens Anchorage International Airport (ANC)",
    "Terrance B. Lettsome International Airport (TUPJ)",
    "Thunder Bay International Airport (CYQT)",
    "Tobías Bolaños International Airport (MRPV)",
    "Tocumen International Airport (MPTO)",
    "Toronto Pearson International Airport (YYZ)",
    "Toussaint Louverture International Airport (MTPP)",
    "Treasure Coast International Airport (FPR)",
    "Trent Lott International Airport (PQL)",
    "Tucson International Airport (TUS)",
    "Tulsa International Airport (TUL)",
    "Union Island International Airport (TVSU)",
    "Uruapan - Licenciado y General Ignacio Lopez Rayon International Airport (MMPN)",
    "V. C. Bird International Airport (TAPA)",
    "Valle del Fuerte International Airport (MMLM)",
    "Valley International Airport (HRL)",
    "Vance W. Amory International Airport (TKPN)",
    "Vancouver International Airport (CYVR)",
    "Victoria International Airport (CYYJ)",
    "Vilo Acuña International Airport (MUCL)",
    "Washington Dulles International Airport (IAD)",
    "Watertown International Airport (ART)",
    "Whitehorse / Erik Nielsen International Airport (CYXY)",
    "Wilkes-Barre/Scranton International Airport (AVP)",
    "William R Fairchild International Airport (CLM)",
    "Williston Basin International Airport (XWA)",
    "Wilmington International Airport (ILM)",
    "Windsor International Airport (CYQG)",
    "Winnipeg / James Armstrong Richardson International Airport (YWG)",
    "Xoxocotlán International Airport (MMOX)",
    "Yellowknife International Airport (CYZF)",
    "Yuma International Airport / Marine Corps Air Station Yuma (NYL)",

    // PAKISTAN
    "Allama Iqbal International Airport (OPLA)",
    "Bacha Khan International Airport (OPPS)",
    "Faisalabad International Airport (OPFA)",
    "Gwadar International Airport (OPGW)",
    "Islamabad International Airport (OPIS)",
    "Jinnah International Airport (OPKC)",
    "Multan International Airport (OPMT)",
    "New Gwadar International Airport (OPGD)",
    "Quetta International Airport (OPQT)",
    "Sialkot International Airport (OPST)",
    "Skardu International Airport (OPSD)",
    "Turbat International Airport (OPTU)",

    // SOUTH AMERICA
    "Alcantarí International Airport (SLAL)",
    "Alejandro Velasco Astete International Airport (SPZO)",
    "Alfonso Bonilla Aragon International Airport (CLO)",
    "Alfredo Vásquez Cobo International Airport (LET)",
    "Andrés Sabella Gálvez International Airport (SCFA)",
    "Aracaju - Santa Maria International Airport (SBAR)",
    "Artigas International Airport (SUAG)",
    "Camilo Daza International Airport (CUC)",
    "Cap FAP David Abenzur Rengifo International Airport (SPCL)",
    "Capitan Corbeta CA Curbelo International Airport (SULS)",
    "Capitán FAP Carlos Martínez de Pinillos International Airport (SPRU)",
    "Capitán FAP José A. Quiñones González International Airport (SPHI)",
    "Captain Pedro Canga Rodríguez International Airport (SPME)",
    "Captain Renán Elías Olivera International Airport (SPSO)",
    "Captain Victor Montes Arias International Airport (SPYL)",
    "Caracas Óscar Machado Zuloaga International Airport (SVCS)",
    "Carlos Concha Torres International Airport (SETN)",
    "Carrasco General Cesáreo L. Berisso International Airport (SUMU)",
    "Carriel Sur International Airport (SCIE)",
    "Cataratas Del Iguazú International Airport (IGU)",
    "Cataratas International Airport (SBFI)",
    "Cerro Largo International Airport (SUMO)",
    "Cheddi Jagan International Airport (SYCJ)",
    "Colonia Laguna de Los Patos International Airport (SUCA)",
    "Comodoro Arturo Merino Benítez International Airport (SCEL)",
    "Coronel FAP Carlos Ciriani Santa Rosa International Airport (SPTN)",
    "Coronel FAP Francisco Secada Vignetta International Airport (SPQT)",
    "Coronel Felipe Varela International Airport (CAT)",
    "Corumbá International Airport (SBCR)",
    "Cotopaxi International Airport (SELT)",
    "Curitiba-Afonso Pena International Airport (SBCT)",
    "Deputado Luiz Eduardo Magalhães International Airport (SBSV)",
    "Eduardo Gomes International Airport (SBEG)",
    "El Alto International Airport (SLLP)",
    "El Calafate - Commander Armando Tola International Airport (ECA)",
    "El Dorado International Airport (BOG)",
    "El Tepual International Airport (SCTE)",
    "Eloy Alfaro International Airport (SEMT)",
    "Ernesto Cortissoz International Airport (BAQ)",
    "Esquel Brigadier Antonio Parodi International Airport (ESQ)",
    "Eugene F. Correia International Airport (SYGO)",
    "Eurico de Aguiar Salles International Airport (SBVT)",
    "Ezeiza International Airport - Ministro Pistarini (EZE)",
    "General Bartolome Salom International Airport (SVPC)",
    "General Enrique Mosconi International Airport (CRV)",
    "General José Antonio Anzoategui International Airport (SVBC)",
    "General Ulpiano Paez International Airport (SESA)",
    "Gobernador Horacio Guzman International Airport (JUJ)",
    "Governador Jorge Teixeira de Oliveira International Airport (SBPV)",
    "Governor Francisco Gabrielli International Airport (DOZ)",
    "Hercílio Luz International Airport (SBFL)",
    "Hermes Quijada International Airport (GRA)",
    "Inca Manco Capac International Airport (SPJL)",
    "Ingeniero Aeronáutico Ambrosio L.V. Taravella International Airport (CBA)",
    "Johan Adolf Pengel International Airport (SMJP)",
    "Jorge Chávez International Airport (SPIM)",
    "Jorge Wilsterman International Airport (SLCB)",
    "Jose Maria Córdova International Airport (MDE)",
    "Josefa Camejo International Airport (SVJC)",
    "José Joaquín de Olmedo International Airport (SEGU)",
    "José Tadeo Monagas International Airport (SVMT)",
    "João Simões Lopes Neto International Airport (SBPK)",
    "Juan Mendoza International Airport (SLOR)",
    "Juan Vicente Gómez International Airport (SVSA)",
    "La Araucanía International Airport (SCQP)",
    "La Chinita International Airport (SVMC)",
    "Lieutenant Colonel Luis A. Mantilla International Airport (SETU)",
    "Macapá - Alberto Alcolumbre International Airport (SBMQ)",
    "Maiquetía Simón Bolívar International Airport (SVMI)",
    "Marechal Cunha Machado International Airport (SBSL)",
    "Mariscal Sucre International Airport (UIO)",
    "Martín Miguel de Güemes International Airport (SAL)",
    "Mataveri International Airport (SCIP)",
    "Matecaña International Airport (PEI)",
    "Mayor Buenaventura Vivas International Airport (SVSO)",
    "Metropolitano International Airport (SVMP)",
    "Ministro Victor Konder International Airport (SBNF)",
    "Mário Pereira Lopes–São Carlos International Airport (SDSC)",
    "Nueva Hesperides International Airport (SUSO)",
    "PAF Captain Guillermo Concha Iberico International Airport (SPUR)",
    "Padre Aldamiz International Airport (SPTU)",
    "Parnaíba - Prefeito Doutor João Silva Filho International Airport (SBPB)",
    "Piloto Civil Norberto Fernández International Airport (GAL)",
    "Pinto Martins International Airport (SBFZ)",
    "Porto Alegre-Salgado Filho International Airport (SBPA)",
    "Porto Seguro International Airport (SBPS)",
    "President Carlos Ibáñez International Airport (SCCI)",
    "Presidente Castro Pinto International Airport (SBJP)",
    "Presidente Juscelino Kubitschek International Airport (SBBR)",
    "Presidente Perón International Airport (NEU)",
    "Rafael Nuñez International Airport (CTG)",
    "Recife/Guararapes - Gilberto Freyre International Airport (SBRF)",
    "Resistencia International Airport (SIS)",
    "Rio Branco-Plácido de Castro International Airport (SBRB)",
    "Rio Galeão – Tom Jobim International Airport (SBGL)",
    "Rio Grande do Norte/São Gonçalo do Amarante–Governador Aluízio Alves International Airport (SBSG)",
    "Rodríguez Ballón International Airport (SPQU)",
    "Rosario Islas Malvinas International Airport (ROS)",
    "Santa Bernardina International Airport (SUDU)",
    "Santa Genoveva International Airport (SBGO)",
    "Santa Rosa - Artillery Colonel Victor Larrea International Airport (SERO)",
    "Santarém - Maestro Wilson Fonseca International Airport (SBSN)",
    "Simón Bolívar International Airport (SMR)",
    "São Paulo/Guarulhos–Governor André Franco Montoro International Airport (SBGR)",
    "Tabatinga International Airport (SBTT)",
    "Tancredo Neves International Airport (SBCF)",
    "Teniente Benjamín Matienzo International Airport (TUC)",
    "Teniente Luis Candelaria International Airport (BAR)",
    "Termas de Río Hondo international Airport (TRH)",
    "Ushuaia - Malvinas Argentinas International Airport (USU)",
    "Val de Cans/Júlio Cezar Ribeiro International Airport (SBBE)",
    "Valle Del Conlara International Airport (SRC)",
    "Viracopos International Airport (SBKP)",
    "Viru Viru International Airport (SLVR)",
    "Várzea Grande–Marechal Rondon International Airport (SBCY)",
    "Zagarzazú International Airport (SUCM)",
    "Zumbi dos Palmares International Airport (SBMO)",
    "Ángel S. Adami International Airport (SUAA)",
    "Ástor Piazzola International Airport (MDP)",
];